<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class QuoteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Create suppliers
                $suppliers = [
                            \App\Models\Supplier::create(['name' => 'Supplier A']),
                                        \App\Models\Supplier::create(['name' => 'Supplier B']),
                                                    \App\Models\Supplier::create(['name' => 'Supplier C']),
                                                            ];
                                                            
                                                                    // Create quotes
                                                                            $quotes = [
                                                                                        \App\Models\Quote::create([
                                                                                                        'name' => 'Summer Collection 2026',
                                                                                                                        'style_number' => 'SC-001',
                                                                                                                                        'status' => 'pending',
                                                                                                                                                        'total' => 0,
                                                                                                                                                                    ]),
                                                                                                                                                                                \App\Models\Quote::create([
                                                                                                                                                                                                'name' => 'Winter Line 2026',
                                                                                                                                                                                                                'style_number' => 'WL-002',
                                                                                                                                                                                                                                'status' => 'approved',
                                                                                                                                                                                                                                                'total' => 0,
                                                                                                                                                                                                                                                            ]),
                                                                                                                                                                                                                                                                    ];
                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                            // Item types for techpack breakdown
                                                                                                                                                                                                                                                                                    $itemTypes = ['Fabric', 'Trim', 'Label', 'Packaging', 'CMT (Labor)', 'Shipping'];
                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                            // Create quote items for each quote and supplier
                                                                                                                                                                                                                                                                                                    foreach ($quotes as $quote) {
                                                                                                                                                                                                                                                                                                                $quoteTotal = 0;
                                                                                                                                                                                                                                                                                                                            foreach ($suppliers as $supplier) {
                                                                                                                                                                                                                                                                                                                                            foreach ($itemTypes as $itemName) {
                                                                                                                                                                                                                                                                                                                                                                $unitPrice = rand(100, 1000) / 100;
                                                                                                                                                                                                                                                                                                                                                                                    $quantity = rand(100, 500);
                                                                                                                                                                                                                                                                                                                                                                                                        $total = $unitPrice * $quantity;
                                                                                                                                                                                                                                                                                                                                                                                                                            $quoteTotal += $total;
                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                \App\Models\QuoteItem::create([
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'quote_id' => $quote->id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'supplier_id' => $supplier->id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'item_name' => $itemName,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'unit_price' => $unitPrice,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'quantity' => $quantity,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'total' => $total,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $quote->update(['total' => $quoteTotal]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }    }
}
