<?php

namespace App\Livewire;

use App\Models\Quote;
use App\Models\ActionPlanItem;
use Filament\Forms\Concerns\InteractsWithForms;
use Filament\Forms\Contracts\HasForms;
use Filament\Tables;
use Filament\Tables\Columns\BadgeColumn;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Concerns\InteractsWithTable;
use Filament\Tables\Contracts\HasTable;
use Filament\Tables\Table;
use Illuminate\Contracts\View\View;
use Illuminate\Database\Eloquent\Builder;
use Livewire\Component;

class QuoteActionPlanTable extends Component implements HasForms, HasTable
{
    use InteractsWithForms;
        use InteractsWithTable;

            public Quote $quote;

                public function table(Table $table): Table
                    {
                            return $table
                                        ->query(
                                                        ActionPlanItem::query()
                                                                            ->where('quote_id', $this->quote->id)
                                                                                                ->orderByRaw("CASE landmark WHEN 'yarn' THEN 1 WHEN 'fabric' THEN 2 WHEN 'cut' THEN 3 WHEN 'sewing' THEN 4 WHEN 'washing' THEN 5 ELSE 6 END")
                                                                                                            )
                                                                                                                        ->columns([
                                                                                                                                        TextColumn::make('landmark')
                                                                                                                                                            ->label('Landmark')
                                                                                                                                                                                ->formatStateUsing(fn (string $state): string => ucfirst($state)),
                                                                                                                                                                                                TextColumn::make('plan_date')
                                                                                                                                                                                                                    ->label('Plan (TNA)')
                                                                                                                                                                                                                                        ->date('M d, Y'),
                                                                                                                                                                                                                                                        TextColumn::make('real_date')
                                                                                                                                                                                                                                                                            ->label('Real (WIP)')
                                                                                                                                                                                                                                                                                                ->date('M d, Y')
                                                                                                                                                                                                                                                                                                                    ->placeholder('-'),
                                                                                                                                                                                                                                                                                                                                    TextColumn::make('delta_days')
                                                                                                                                                                                                                                                                                                                                                        ->label('Δ days')
                                                                                                                                                                                                                                                                                                                                                                            ->color('danger')
                                                                                                                                                                                                                                                                                                                                                                                                ->formatStateUsing(fn ($state): string => $state !== null ? ($state > 0 ? '+' . $state : (string) $state) : ''),
                                                                                                                                                                                                                                                                                                                                                                                                                BadgeColumn::make('state')
                                                                                                                                                                                                                                                                                                                                                                                                                                    ->label('State')
                                                                                                                                                                                                                                                                                                                                                                                                                                                        ->colors([
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'success' => 'completed',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'danger' => 'delayed',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'warning' => 'pending',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ->formatStateUsing(fn (string $state): string => ucfirst($state)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ->paginated(false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        public function render(): View
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return view('livewire.quote-action-plan-table');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }